from typing import Set, Dict, Any, Optional
from dataclasses import dataclass

# Use canonical Role and Permission from agent.core.types to ensure consistency
from agent.core.types import Role, Permission

@dataclass
class AccessRule:
    role: Role
    permission: Permission
    resource: str = "*"

# sensible default permissions map
DEFAULT_ROLE_PERMISSIONS: Dict[Role, Set[Permission]] = {
    Role.ADMIN: set(p for p in Permission),
    Role.DEVELOPER: {Permission.EXECUTE_AGENT, Permission.READ_MEMORY},
    Role.USER: {Permission.EXECUTE_AGENT},
    Role.GUEST: {Permission.QUERY_READONLY},
}

class GovernancePolicy:
    """Minimal policy container"""
    def __init__(self, rules=None):
        self.rules = rules or []

    def allows(self, role: Role, permission: Permission, resource: str = "*") -> bool:
        # simple check against defaults then explicit rules
        if permission in DEFAULT_ROLE_PERMISSIONS.get(role, set()):
            return True
        for r in self.rules:
            if r.role == role and r.permission == permission and (r.resource == resource or r.resource == "*"):
                return True
        return False

    def evaluate_access(self, subject, action: str, resource, ctx):
        """Compatibility shim: return object with .allow attribute.
        Accepts subject.role as enum or string. Maps action string to Permission when possible.
        """
        role_val = getattr(subject, 'role', subject)
        if hasattr(role_val, 'value'):
            role_val = role_val.value
        try:
            role_enum = Role(role_val)
        except Exception:
            return type('D', (), {'allow': False})()
        # map action ("memory:read") to Permission if possible
        perm = None
        if isinstance(action, str):
            try:
                perm = Permission(action)
            except Exception:
                # try mapping by name (e.g. 'QUERY_READONLY')
                try:
                    perm = Permission[action]
                except Exception:
                    perm = None
        if perm is None:
            # fallback to a safe permission-like default
            perm = Permission.EXECUTE_AGENT
        allowed = self.allows(role_enum, perm, getattr(resource, 'type', '*'))
        return type('D', (), {'allow': allowed})()

class RBACManager:
    def __init__(self, policy: GovernancePolicy | None = None):
        self.policy = policy or GovernancePolicy()

    def check_permission(self, role: Role, permission: Permission, resource: str = "*") -> bool:
        return self.policy.allows(role, permission, resource)

    def grant_permission(self, role: Role, permission: Permission):
        DEFAULT_ROLE_PERMISSIONS.setdefault(role, set()).add(permission)

    def revoke_permission(self, role: Role, permission: Permission):
        DEFAULT_ROLE_PERMISSIONS.setdefault(role, set()).discard(permission)

def enforce_access(role: Role, permission: Permission, manager: RBACManager | None = None) -> bool:
    """Utility to enforce access; returns True if allowed, False otherwise."""
    mgr = manager or RBACManager()
    return mgr.check_permission(role, permission)

# Rbac PoC class expected by autogenerated tests
class Rbac:
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    def execute(self, *args, **kwargs):
        return {"module": "rbac", "ok": True}

# Exported names expected by package __init__
__all__ = [
    'AccessRule',
    'DEFAULT_ROLE_PERMISSIONS',
    'GovernancePolicy',
    'RBACManager',
    'enforce_access',
    'Rbac',
]
