"""
Multiagent Framework - Cluster Module (compat shim + PoC)
Provides AgentRegistry, AgentInfo, AgentConfig, ClusterScaler and Cluster minimal implementations for imports/tests.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from agent.core.errors import AgentAlreadyRegisteredError, AgentNotFoundError


@dataclass
class AgentInfo:
    id: str
    role: str = "worker"
    capabilities: List[str] = None
    state: str = "INITIALIZED"
    task_count: int = 0
    current_load: float = 0.0
    available_cpu: float = 1.0
    available_memory: float = 1.0
    uptime: float = 0.0
    failure_rate: float = 0.0


@dataclass
class AgentConfig:
    config: Dict[str, Any]


class AgentRegistry:
    def __init__(self):
        self.agents: Dict[str, AgentInfo] = {}

    async def register_agent(self, info: AgentInfo):
        if info.id in self.agents:
            raise AgentAlreadyRegisteredError(info.id)
        self.agents[info.id] = info
        return info

    async def unregister_agent(self, agent_id: str):
        if agent_id not in self.agents:
            raise AgentNotFoundError(agent_id)
        del self.agents[agent_id]

    async def discover_agents(self, role: Optional[str] = None):
        res = [a for a in self.agents.values() if (role is None or a.role == role)]
        return res

    def list_agents(self):
        return list(self.agents.values())


class ClusterScaler:
    def __init__(self, lifecycle_manager=None):
        self.lifecycle = lifecycle_manager
        self.scale = 1

    async def scale_up(self, n: int):
        created = []
        for i in range(n):
            # create synthetic agent entries
            aid = (
                f"agent_scaled_{len(self.lifecycle.agents)+1 if self.lifecycle else i}"
            )
            info = AgentInfo(id=aid)
            if self.lifecycle:
                await self.lifecycle.create_agent(info)
            created.append(info)
        return created


class Cluster:
    """Compatibility Cluster PoC used by autogenerated tests."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    def execute(self, *args, **kwargs) -> Dict[str, Any]:
        return {"module": "cluster", "ok": True}


__all__ = ["AgentRegistry", "AgentInfo", "AgentConfig", "ClusterScaler", "Cluster"]
