"""
Memory Framework - Layers Module (compat shim + Layers PoC)
Provides MemoryLayer base, ImmediateContextMemory, SemanticMemory, Session/Episodic/Archive stubs,
LRUCache import and Layers PoC used by autogenerated tests.
"""
from __future__ import annotations
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional
from .lru import LRUCache

class MemoryLayer:
    """Base memory layer interface"""
    def __init__(self, name: str, ttl: Optional[timedelta] = None):
        self.name = name
        self.ttl = ttl
        self.storage: Dict[str, Any] = {}
        self.created_at: Dict[str, datetime] = {}

    def now(self) -> datetime:
        return datetime.now(timezone.utc)

    def store(self, key: str, value: Any) -> None:
        self.storage[key] = value
        self.created_at[key] = self.now()

    def retrieve(self, key: str) -> Optional[Any]:
        if key not in self.storage:
            return None
        if self.ttl and (self.now() - self.created_at[key]) > self.ttl:
            del self.storage[key]
            del self.created_at[key]
            return None
        return self.storage[key]

    def search(self, query: str, limit: int = 10) -> List[Any]:
        results: List[Any] = []
        for k, v in self.storage.items():
            if query.lower() in str(v).lower():
                results.append(v)
                if len(results) >= limit:
                    break
        return results

class ImmediateContextMemory(MemoryLayer):
    def __init__(self):
        super().__init__("immediate", ttl=timedelta(hours=2))

class SemanticMemory(MemoryLayer):
    """Stub semantic memory for embeddings-backed storage (mocked for tests)
    Provides index and query semantics but stores plain values for PoC.
    """
    def __init__(self):
        super().__init__("semantic", ttl=None)
        # simple list index
        self.index: List[Dict[str, Any]] = []

    def index_item(self, id: str, vector: List[float], payload: Any):
        self.index.append({"id": id, "vector": vector, "payload": payload})

    def query_vector(self, vector: List[float], top_k: int = 5) -> List[Any]:
        # PoC: return first top_k payloads
        return [e['payload'] for e in self.index[:top_k]]

class SessionMemory(MemoryLayer):
    """Minimal session-scoped memory (episodic short-lived between requests)
    Async/sync interfaces not required for PoC: simple wrapper around MemoryLayer.
    """
    def __init__(self):
        super().__init__("session", ttl=timedelta(hours=1))

class EpisodicMemory(MemoryLayer):
    """Episodic memory across a conversation/session with longer TTL."""
    def __init__(self):
        super().__init__("episodic", ttl=timedelta(days=1))

class ArchiveMemory(MemoryLayer):
    """Archive storage (cold) - readonly PoC interface."""
    def __init__(self):
        super().__init__("archive", ttl=None)

    def archive_item(self, key: str, value: Any):
        # append-only behavior
        self.storage[key] = value

class Layers:
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.immediate = ImmediateContextMemory()
        self.semantic = SemanticMemory()
        self.session = SessionMemory()
        self.episodic = EpisodicMemory()
        self.archive = ArchiveMemory()
        self.cache = LRUCache()

    def execute(self, *args, **kwargs):
        return {"module": "layers", "ok": True}

__all__ = ["MemoryLayer", "ImmediateContextMemory", "SemanticMemory", "SessionMemory", "EpisodicMemory", "ArchiveMemory", "Layers", "LRUCache"]
