"""
Memory Framework - Layers Module (compat shim + Layers PoC)
Provides MemoryLayer base, ImmediateContextMemory, SemanticMemory, Session/Episodic/Archive stubs,
LRUCache import and Layers PoC used by autogenerated tests.
"""
from __future__ import annotations
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional
from .lru import LRUCache
from .layers_types import KnowledgeItem, SessionRecord

class MemoryLayer:
    """Base memory layer interface"""
    def __init__(self, name: str, ttl: Optional[timedelta] = None):
        self.name = name
        self.ttl = ttl
        self.storage: Dict[str, Any] = {}
        self.created_at: Dict[str, datetime] = {}

    def now(self) -> datetime:
        return datetime.now(timezone.utc)

    def store(self, key: str, value: Any) -> None:
        self.storage[key] = value
        self.created_at[key] = self.now()

    def retrieve(self, key: str) -> Optional[Any]:
        if key not in self.storage:
            return None
        created = self.created_at.get(key)
        if self.ttl and created is not None:
            # guard against naive datetimes set by tests or external code
            try:
                if created.tzinfo is None:
                    from datetime import timezone
                    created = created.replace(tzinfo=timezone.utc)
            except Exception:
                pass
            if (self.now() - created) > self.ttl:
                del self.storage[key]
                del self.created_at[key]
                return None
        return self.storage[key]

    def search(self, query: str, limit: int = 10) -> List[Any]:
        results: List[Any] = []
        for k, v in self.storage.items():
            if query.lower() in str(v).lower():
                results.append(v)
                if len(results) >= limit:
                    break
        return results

class ImmediateContextMemory(MemoryLayer):
    def __init__(self, max_size: Optional[int] = None, **kwargs):
        # Accept max_size for compatibility with tests; unused in PoC but stored.
        super().__init__("immediate", ttl=timedelta(hours=2))
        self.max_size = max_size or 1024
        # conversation turns storage (list of dict-like entries)
        self.turns: List[Dict[str, Any]] = []
        # execution state store
        self.execution_state: Dict[str, Any] = {}
        # attention stack
        self.attention_stack: List[Any] = []

    def record_conversation_turn(self, user_message: str, agent_response: str) -> Dict[str, Any]:
        t = {
            'timestamp': self.now(),
            'user_message': user_message,
            'agent_response': agent_response,
        }
        self.turns.append(t)
        # trim to max_size for conversation history
        if len(self.turns) > self.max_size:
            self.turns = self.turns[-self.max_size:]
        return t

    def get_conversation_context(self, window_size: int = 5) -> Any:
        # return a simple context object with required attributes
        window = self.turns[-window_size:]
        ctx = type('Ctx', (), {})()
        ctx.conversation_state = 'active' if window else 'idle'
        ctx.last_turn_time = window[-1]['timestamp'] if window else None
        return ctx

    def update_execution_state(self, new_state: Dict[str, Any]) -> None:
        self.execution_state.update(new_state)

    def get_attention_context(self) -> Any:
        ac = type('AC', (), {})()
        ac.primary = self.attention_stack[0] if self.attention_stack else None
        ac.secondary = self.attention_stack[1:] if len(self.attention_stack) > 1 else []
        ac.focus_strength = (1.0 / len(self.attention_stack)) if self.attention_stack else 0.0
        return ac

class SemanticMemory(MemoryLayer):
    """Stub semantic memory for embeddings-backed storage (mocked for tests)
    Provides index and query semantics but stores plain values for PoC.
    """
    def __init__(self, dim: int = 128):
        super().__init__("semantic", ttl=None)
        # simple list index
        self.index: List[Dict[str, Any]] = []
        self.dim = dim
        # PoC semantic index holder and embedding model stub used by tests
        class _IndexShim:
            def __init__(self):
                self._ids = set()
            def add(self, id, vector=None):
                self._ids.add(id)
            def __contains__(self, id):
                return id in self._ids
        self.semantic_index = _IndexShim()
        class EmbStub:
            def __init__(self, dim):
                self.dim = dim
            def embed(self, text):
                return [0.0]*self.dim
        self.embedding_model = EmbStub(dim)

    def index_item(self, id: str, vector: List[float], payload: Any):
        self.index.append({"id": id, "vector": vector, "payload": payload})

    def store_knowledge_item(self, item: KnowledgeItem):
        # assign id if missing
        if not getattr(item, 'knowledge_id', None):
            item.knowledge_id = f"k_{len(self.index)+1}"
        self.index.append({"id": item.knowledge_id, "payload": item})
        self.storage[item.knowledge_id] = item
        return item

    def semantic_search(self, query: str, top_k: int = 5) -> List[KnowledgeItem]:
        # PoC: return items whose content contains query. Be permissive about payload types
        res = []
        q = query.lower()
        for e in self.index:
            payload = e.get('payload')
            text = None
            # accept dataclass-like or dict-like payloads
            if hasattr(payload, 'content'):
                text = getattr(payload, 'content')
            elif isinstance(payload, dict):
                text = payload.get('content')
            if text and q in str(text).lower():
                res.append(payload)
                if len(res) >= top_k:
                    break
        # Fallback: if index yielded nothing, search stored items directly (robustness for PoC)
        if not res:
            for v in self.storage.values():
                text = None
                if hasattr(v, 'content'):
                    text = getattr(v, 'content')
                elif isinstance(v, dict):
                    text = v.get('content')
                if text and q in str(text).lower():
                    res.append(v)
                    if len(res) >= top_k:
                        break
        return res

    def build_knowledge_graph(self):
        # PoC: build a simple knowledge graph structure with nodes and edges.
        nodes: List[Dict[str, Any]] = []
        edges: List[Dict[str, Any]] = []
        seen = set()
        for e in self.index:
            nid = e.get('id')
            payload = e.get('payload')
            concepts = getattr(payload, 'concepts', []) if payload is not None else []
            nodes.append({'id': nid, 'concepts': concepts})
            seen.add(nid)
        for sid, v in self.storage.items():
            if sid not in seen and hasattr(v, 'knowledge_id'):
                nodes.append({'id': sid, 'concepts': getattr(v, 'concepts', [])})
                seen.add(sid)
        for sid, v in self.storage.items():
            rels = getattr(v, 'relationships', []) or []
            for r in rels:
                target = r.get('target_id')
                etype = r.get('type', 'related')
                strength = r.get('strength', 0.0)
                if target and target not in seen:
                    nodes.append({'id': target, 'concepts': []})
                    seen.add(target)
                edges.append({'source': sid, 'target': target, 'type': etype, 'strength': strength})
        return {'nodes': nodes, 'edges': edges}

class SessionMemory(MemoryLayer):
    """Minimal session-scoped memory (episodic short-lived between requests)
    Async/sync interfaces not required for PoC: simple wrapper around MemoryLayer.
    """
    def __init__(self, ttl: Optional[timedelta] = None):
        super().__init__("session", ttl=ttl or timedelta(hours=1))

class EpisodicMemory(MemoryLayer):
    """Episodic memory across a conversation/session with longer TTL."""
    def __init__(self, ttl: Optional[timedelta] = None):
        super().__init__("episodic", ttl=ttl or timedelta(days=1))
        # event log for PoC
        self.events: List[Any] = []

    def record_event(self, event: Any):
        """Record a SystemEvent-like object into episodic storage.

        Returns a small reference object with attribute `event_id` and `timestamp`.
        """
        # store event by generated id if not provided
        eid = getattr(event, 'event_id', None) or f"evt_{len(self.events)+1}"
        ts = getattr(event, 'timestamp', self.now())
        self.events.append({'id': eid, 'event': event, 'timestamp': ts})
        # also record created_at for expiry checks
        self.created_at[eid] = ts
        class EventRef:
            def __init__(self, event_id, timestamp):
                self.event_id = event_id
                self.timestamp = timestamp
        return EventRef(event_id=eid, timestamp=ts)

    def extract_learned_patterns(self, time_window: Optional[timedelta] = None) -> List[Any]:
        """Simple PoC pattern extraction.

        Returns a list of pattern-like objects with attribute 'pattern_type'.
        Detects two simple patterns:
          - 'success_sequence': two or more consecutive success events within window
          - 'failure_recovery': a failure event followed by a success event within window
        """
        now = self.now()
        # filter events within window
        if time_window:
            cutoff = now - time_window
            seq = [e for e in self.events if e['timestamp'] >= cutoff]
        else:
            seq = list(self.events)
        patterns: List[Any] = []
        # detect success_sequence
        consec = 0
        for item in seq:
            ev = item['event']
            ok = getattr(ev, 'success', None)
            if ok:
                consec += 1
            else:
                consec = 0
            if consec >= 2:
                p = type('P', (), {})()
                p.pattern_type = 'success_sequence'
                patterns.append(p)
                break
        # detect failure_recovery
        for i in range(len(seq)-1):
            ev1 = seq[i]['event']
            ev2 = seq[i+1]['event']
            if getattr(ev1, 'success', None) is False and getattr(ev2, 'success', None) is True:
                p = type('P', (), {})()
                p.pattern_type = 'failure_recovery'
                patterns.append(p)
                break
        return patterns


class ArchiveMemory(MemoryLayer):
    """Archive storage (cold) - readonly PoC interface."""
    def __init__(self):
        super().__init__("archive", ttl=None)

    def archive_item(self, key: str, value: Any):
        # append-only behavior
        self.storage[key] = value

    def archive_session(self, session: SessionRecord):
        aid = f"arc_{len(self.storage)+1}"
        path = f"archive://sessions/{aid}"
        self.storage[aid] = session
        class Ref:
            def __init__(self, archive_id, archive_path):
                self.archive_id = archive_id
                self.archive_path = archive_path
        return Ref(archive_id=aid, archive_path=path)

    def retrieve_archived_session(self, archive_id: str) -> Optional[SessionRecord]:
        # If a separate data slot exists and contains corrupted bytes, raise ArchiveCorruptedError
        data_key = f"{archive_id}:data"
        if data_key in self.storage:
            val = self.storage[data_key]
            if isinstance(val, (bytes, bytearray)):
                from agent.core.errors import ArchiveCorruptedError
                raise ArchiveCorruptedError(f"archive {archive_id} data corrupted")
        return self.storage.get(archive_id)

class Layers:
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.immediate = ImmediateContextMemory()
        self.semantic = SemanticMemory()
        self.session = SessionMemory()
        self.episodic = EpisodicMemory()
        self.archive = ArchiveMemory()
        self.cache = LRUCache()

    def execute(self, *args, **kwargs):
        return {"module": "layers", "ok": True}

__all__ = ["MemoryLayer", "ImmediateContextMemory", "SemanticMemory", "SessionMemory", "EpisodicMemory", "ArchiveMemory", "Layers", "LRUCache", "KnowledgeItem", "SessionRecord"]
