"""
Orchestration Framework - Executor Module (compat shim + PoC)
Provides Executor class expected by autogenerated tests plus OrchestrationEngine.
"""
import asyncio

from typing import Any, Dict, Optional
from agent.core.errors import RateLimitError

class Executor:
    """Executor module (PoC)
    """
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    def execute(self, *args, **kwargs) -> Any:
        """Placeholder execute"""
        return {"module": "executor", "ok": True}

class ErrorHandlingStrategy:
    def __init__(self, skill_registry: Optional[Dict[str, Any]] = None, default_strategy: str = 'retry_on_transient'):
        self.skill_registry = skill_registry or {}
        self.default_strategy = default_strategy

    def categorize_error(self, err: Exception) -> str:
        # PoC categorization
        if isinstance(err, TimeoutError) or isinstance(err, asyncio.TimeoutError):
            return 'TIMEOUT'
        # handle test-local RateLimitError classes (by name) or the shared one
        if isinstance(err, RateLimitError) or getattr(getattr(err, '__class__', None), '__name__', '') == 'RateLimitError':
            return 'NETWORK_ERROR'
        try:
            from agent.core.errors import ConnectionError
            if isinstance(err, ConnectionError):
                return 'TRANSIENT'
        except Exception:
            pass
        return 'GENERIC_ERROR'

    def get_recovery_action(self, strategy: Dict[str, Any]):
        # strategy is a dict containing action and params
        # return a dataclass-like object with attribute access expected by tests
        try:
            from agent.core.types import RecoveryAction
            action = strategy.get('action') if isinstance(strategy, dict) else getattr(strategy, 'action', None)
            fallback = strategy.get('fallback_skill') if isinstance(strategy, dict) else getattr(strategy, 'fallback_skill', None)
            return RecoveryAction(action=action or 'STOP', fallback_skill=fallback)
        except Exception:
            # fallback: return a simple object
            class RA:
                def __init__(self, d):
                    self.action = d.get('action') if isinstance(d, dict) else getattr(d, 'action', None)
                    self.fallback_skill = d.get('fallback_skill') if isinstance(d, dict) else getattr(d, 'fallback_skill', None)
            return RA(strategy)

    def select_recovery_strategy(self, task: Any = None, err_type: str = '', retry_count: int = 0, default_strategy: Optional[str] = None) -> Dict[str, Any]:
        """Select a recovery strategy for a given task and error type.
        PoC logic:
         - If default_strategy == 'retry_on_transient' and retry_count >= 3 -> STOP
         - If err_type == 'TIMEOUT' -> RETRY
         - If err_type == 'NETWORK_ERROR' -> FALLBACK
         - Otherwise return {'action': 'STOP'}
        """
        strategy = default_strategy or self.default_strategy
        if strategy == 'retry_on_transient' and retry_count >= 3:
            return {'action': 'STOP'}
        if err_type == 'TIMEOUT':
            return {'action': 'RETRY'}
        if err_type == 'NETWORK_ERROR':
            return {'action': 'FALLBACK', 'fallback_skill': 'alternative_skill'}
        return {'action': 'STOP'}

class OrchestrationEngine:
    def __init__(self):
        self.state = {}

    def run(self, dag, planner, executor):
        results = {}
        for nid in dag.nodes:
            results[nid] = executor.execute(nid)
        return results

__all__ = ['Executor', 'OrchestrationEngine', 'ErrorHandlingStrategy']
