"""
Automation Framework - Scheduler Module (compat shim + PoC)
Provides Scheduler class expected by autogenerated tests plus other shims.
"""

from typing import Any, Dict, List, Optional, Tuple


class Scheduler:
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    def execute(self, *args, **kwargs):
        return {"module": "scheduler", "ok": True}


class PriorityQueue:
    def __init__(self):
        self.q: List[Tuple[int, Any]] = []

    # compatibility API: put/get expected by tests
    def put(self, item, priority: int = 0):
        self.q.append((priority, item))
        # keep highest priority first
        self.q.sort(reverse=True)

    def get(self):
        if not self.q:
            raise IndexError("empty")
        return self.q.pop(0)[1]


class SchedulingEngine:
    def __init__(self):
        self.workflows = []

    def register_workflow(self, wf):
        self.workflows.append(wf)

    async def schedule_workflow(self, wf):
        # return a simple Job object (awaitable for compatibility)
        class Job:
            def __init__(self, priority=0, retries=0):
                self.priority = getattr(wf, "priority", priority)
                self.retries_remaining = getattr(wf, "max_retries", retries)

        return Job(
            priority=getattr(wf, "priority", 0), retries=getattr(wf, "max_retries", 0)
        )

    async def execute_job(self, job, run_fn=None):
        # simulate execution result (awaitable)
        class Result:
            def __init__(self, status="SUCCESS", retries_remaining=0):
                self.status = status
                self.retries_remaining = retries_remaining

        # If a run function (async or callable) is provided, call it and handle failures with retries
        if run_fn is not None:
            try:
                res = run_fn(job)
                # if it's awaitable, await it
                import inspect

                if inspect.isawaitable(res):
                    await res
                return Result(
                    status="SUCCESS",
                    retries_remaining=getattr(job, "retries_remaining", 0),
                )
            except Exception:
                rem = getattr(job, "retries_remaining", 0)
                if rem > 0:
                    job.retries_remaining = rem - 1
                    return Result(
                        status="RETRY", retries_remaining=job.retries_remaining
                    )
                else:
                    return Result(status="FAILURE", retries_remaining=0)

        return Result(
            status="SUCCESS", retries_remaining=getattr(job, "retries_remaining", 0)
        )


class ResourceAwareScheduler:
    def schedule(self, tasks, resources=None):
        return tasks

    def optimize_scheduling_order(self, jobs, resource_snapshot=None):
        """Return jobs ordered by priority desc, simple resource-aware placeholder.
        Accepts objects with .priority attribute. resource_snapshot is currently unused.
        """
        try:
            return sorted(jobs, key=lambda j: getattr(j, "priority", 0), reverse=True)
        except Exception:
            return jobs


__all__ = ["Scheduler", "PriorityQueue", "SchedulingEngine", "ResourceAwareScheduler"]
