"""
Automation Framework - Triggers Module (PoC)
Provides Triggers class with config/execute API used by autogenerated tests and keeps compatibility names.
Updated: make execute_triggered_workflow async to satisfy tests that call asyncio.run(...)
"""
from typing import Any, Dict, List, Optional
from dataclasses import dataclass
import uuid

@dataclass
class Trigger:
    trigger_id: str
    trigger_type: str
    workflow_id: Optional[str] = None
    enabled: bool = True

@dataclass
class TriggerContext:
    pass

class TriggerExecutor:
    def __init__(self, workflow_registry: Optional[Dict[str, Any]] = None):
        self.workflow_registry = workflow_registry or {}

    def run(self, trigger):
        return {"ok": True}

    async def execute_triggered_workflow(self, trigger: Trigger, ctx: TriggerContext):
        # return a minimal execution record as an awaitable
        class Exec:
            def __init__(self, workflow_id):
                self.workflow_id = workflow_id

        return Exec(workflow_id=trigger.workflow_id)

class TriggerManager:
    def __init__(self):
        self.triggers: Dict[str, Trigger] = {}

    def register(self, t: Dict[str, Any]):
        trig_type = t.get('trigger_type','schedule')
        allowed = {'schedule', 'webhook', 'event', 'cron'}
        if trig_type not in allowed:
            raise ValueError(f"unsupported trigger_type: {trig_type}")
        trig = Trigger(trigger_id=str(uuid.uuid4()), trigger_type=trig_type, workflow_id=t.get('workflow_id'))
        self.triggers[trig.trigger_id] = trig
        return trig

    # compatibility names expected by tests
    def register_trigger(self, workflow_id: str, trigger: Trigger):
        # assign id if missing
        if not getattr(trigger, 'trigger_id', None):
            trigger.trigger_id = str(uuid.uuid4())
        allowed = {'schedule', 'webhook', 'event', 'cron'}
        if getattr(trigger, 'trigger_type', None) not in allowed:
            raise ValueError(f"unsupported trigger_type: {getattr(trigger,'trigger_type',None)}")
        self.triggers[trigger.trigger_id] = trigger
        return trigger

    def get_trigger(self, trigger_id: str):
        return self.triggers.get(trigger_id)

class Triggers:
    """Plural-compatible wrapper used by some callers/tests."""
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.manager = TriggerManager()

    def execute(self, *args, **kwargs) -> Dict[str, Any]:
        return {"module": "triggers", "ok": True}

    # delegate commonly expected manager APIs
    def register_trigger(self, workflow_id: str, trigger: Trigger):
        return self.manager.register_trigger(workflow_id, trigger)

    def get_trigger(self, trigger_id: str):
        return self.manager.get_trigger(trigger_id)

__all__ = ['Triggers', 'TriggerManager', 'TriggerExecutor', 'Trigger', 'TriggerContext']
